OpenSpace/OpenSpace-WebGui

- src/components/Tooltip/Tooltip.tsx
- src/panels/FlightControlPanel/FlightControlPanel.tsx
- src/panels/FlightControlPanel/FlightController.tsx
- src/redux/flightcontroller/flightControllerSlice.ts
- src/redux/propertytree/properties/propertiesSlice.ts
- src/redux/store.ts
- src/types/flightcontroller-types.d.ts
- src/util/keys.ts
- src/windowmanagement/WindowLayout/WindowLayout.tsx
- src/windowmanagement/data/MenuItems.tsx
Changes from the old system: 
The flight control panel is now for settings only. The interaction happens in the main window (empty space) of the gui
> add flight controller

- src/api/LuaApiProvider.tsx
- src/api/hooks.ts
- src/redux/connection/connectionMiddleware.ts
- src/redux/connection/connectionSlice.ts
- src/redux/events/eventsMiddleware.ts
- src/redux/propertytree/properties/propertiesMiddleware.ts
- src/redux/sessionrecording/sessionRecordingMiddleware.ts
- src/redux/time/timeMiddleware.ts
- src/types/enums.ts
- src/windowmanagement/ConnectionErrorOverlay.tsx
Also enables the reload button again on connection lost😄
> add modal when webpage is trying to connect to OpenSpace

- src/panels/OriginPanel/FocusEntry.tsx
> Fix text wrapping and truncating

- src/panels/OriginPanel/OriginPanelMenuButton.tsx
- src/panels/TimePanel/TimePanelMenuButton.tsx
Every time I open the UI I thought about that we should do this, so now I did it so I don't have to think about it anymore :)
> Add loading state to focus and time button

- src/panels/Scene/GlobeLayers/GlobeLayersGroup.tsx
- src/util/propertyTreeHelpers.ts
> Add hints for how many layers there are in each layer group

- src/panels/Scene/SceneTree/SceneTreeNode.tsx
> Update visuals for currently selected scene graph node in scene tree

- src/panels/Menu/TopMenuBar/Menus/FileMenu.tsx
* Removes the add asset option from the top menu bar
> Remove add asset

- src/theme/mantineTheme.module.css
- src/theme/mantineTheme.ts
* Fixes the focus issue in the bottom bar
> Make highlight of items be inside the object

- src/panels/TimePanel/TimePanelMenuButton.tsx
* Fixes the issues with the time panel menu button
> Fix time panel menu button issues

- src/App.tsx
- src/icons/icons.tsx
- src/panels/GettingStartedPanel/Tasks/Components/TaskCheckbox.tsx
- src/panels/SkyBrowserPanel/BrowserTabs/BrowserTabs.tsx
- src/panels/SkyBrowserPanel/BrowserTabs/Settings.tsx
- src/panels/SkyBrowserPanel/BrowserTabs/TabContent.tsx
* Adds close button to skybrowser tab
* Changes the styling of the skybrowser tab 
* This has the benefit of showing the color in a neater way, and not looking confusingly similar to the window tabs
> Skybrowser close button

- src/components/Input/NumericInput/NumericInput.tsx
- src/panels/TimePanel/TimeInput/TimeInput.tsx
- src/windowmanagement/data/MenuItems.tsx
Changes the outline in the time panel when pressing the lock icon to another type of outline
> Fix outline confusion in time panel

- src/components/FilterList/FilterListInputField.tsx
Making this a PR since I want a thumbs up for the updated styling fo the button. The old one blended in with the input field and all the surrounding buttons in a way I didn't like. 
Other suggestions are welcome!
Now VS before
> Fixed width and update style for More/Less button in filterlist

- src/icons/icons.tsx
- src/panels/GettingStartedPanel/GettingStartedPanel.tsx
- src/panels/GettingStartedPanel/Steps/ContentSteps.tsx
- src/panels/GettingStartedPanel/Steps/TimeSteps.tsx
Mainly to remove pointer events for illustrative input components. Note that it was not possible for the more custom ones, like time increment and SGN header
> Small updates to getting started tour

- src/components/Property/Types/OptionProperty.tsx
- src/redux/propertytree/properties/propertiesMiddleware.ts
- src/redux/propertytree/properties/propertiesSlice.ts
- src/redux/propertytree/propertyTreeMiddleware.ts
- src/types/types.ts
Adds the options that are added dynamically to option property
https://github.com/OpenSpace/OpenSpace/issues/3342#issue-2383863785
> Add update to redux for when option properties change their options

- src/cef-globals.d.ts
- src/windowmanagement/data/MenuItems.tsx
Checks if webpage is in browser or cef and sets the flightcontroller panel visibility accordingly
> Add within cef flag that is set from C++

- src/icons/icons.tsx
- src/panels/DevPanel/DevPanel.tsx
- src/panels/DevPanel/Subpanels/PropertyTest.tsx
- src/windowmanagement/data/MenuItems.tsx
where we can sollect other useful dev specific panels in the future
> Move Property test panel into a "Dev panel"

- src/panels/Menu/TopMenuBar/Menus/FileMenu.tsx
- src/panels/Menu/TopMenuBar/TopMenuBar.tsx
- src/redux/profile/profileSlice.ts
Also adds some more information about the profile, such as the description, file path, author, and license. I skipped showing the version in the UI as of now, thinking that this might be more confusing than useful. 
Use together with OpenSpace PR: OpenSpace/OpenSpace#3628
> Move profile name from top bar center to File menu

- package-lock.json
- package.json
- src/windowmanagement/WindowLayout/WindowLayoutProvider.tsx
#fixes https://github.com/OpenSpace/OpenSpace/issues/3636
> increase default panel size to 350px

- public/locales/en/components.json
- src/components/CopyUriButton/CopyUriButton.tsx
- src/panels/ActionsPanel/ActionsButton.tsx
I think we can consider this a bug fix 😇
> Update copy URI component to include URI, and fix URI for actions

- src/components/ColorPicker/ColorPicker.tsx
- src/util/colorHelper.ts
There was an issue with mantine's `toRgba` function so made a PR for that in their repo and also a temporary fix here
Closes https://github.com/OpenSpace/OpenSpace/issues/3688#issue-3090980573
> Fix issue with alpha value with color slider

- public/locales/en/panel-exoplanets.json
- src/panels/ExoplanetsPanel/ExoplanetsPanel.tsx
To include size of dataset, like we do for skybrowser images
After: 
Before:
> Update search placeholder for exoplanets

- README.md
- public/locales/en/menu.json
- public/locales/en/panel-gettingstartedtour.json
- src/icons/icons.tsx
- src/panels/Menu/Toolbar/Toolbar.tsx
- src/panels/Menu/Toolbar/ToolbarMenuButton.tsx
- src/panels/Menu/TopMenuBar/Menus/ViewMenu.tsx
- src/panels/Menu/hooks.ts
- src/panels/Menu/types.ts
- src/panels/NavigationPanel/MenuButton/NavigationPanelMenuButton.tsx
- src/panels/SessionRecordingPanel/SessionRecordingMenuButton.tsx
- src/redux/local/localSlice.ts
- src/redux/local/util.ts
- src/redux/profile/profileMiddleware.ts
- src/windowmanagement/WindowLayout/WindowLayout.tsx
- src/windowmanagement/data/MenuItems.tsx
closes OpenSpace/OpenSpace#3725
> Rename "Task bar" to "Toolbar" (OpenSpace/OpenSpace#3725)

- src/components/Property/PropertyDescription.tsx
fixes https://github.com/OpenSpace/OpenSpace/issues/3648
> Break long words in property info tooltips

- src/hooks/propertyOwner.ts
> Shift+Click toggling sets property values directly instead of using fade functions
